### ISSUE TITLE
建议把cn域名direct后置

### ISSUE THREAD

**Issue by GHDeepUser** [XinSSS/Conf-for-Surge-Shadowrocket#5]
用的IOS SR，测试 http://edmontonchina.cn/ （被q）在规则列表默认是proxy，但是由于“domain-suffix, cn, direct”规则在前，SR默认首先匹配direct，导致无法访问，建议cn这类大域名规则后置，我放在final规则前，没问题^_^

**Comment by XinSSS** [comment]
OK,已经调整
